name: Deploy Backend
on:
  push:
    branches: [main, develop]

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener cÃ³digo
        uses: actions/checkout@v3
      
      - name: Login en GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Construir y subir Backend
        run: |
          echo " Construyendo Backend..."
          REPO_NAME_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          docker build -t ghcr.io/$REPO_NAME_LC/backend:latest \
            -f workpoint.Api/Dockerfile \
            .
          
          docker push ghcr.io/$REPO_NAME_LC/backend:latest
          echo " Backend listo"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Instalar SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: 'placeholder'
      
      - name: Agregar Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      
      - name: Desplegar en VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
            echo " Desplegando Backend..."
            
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            REPO_NAME_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            
            docker pull ghcr.io/$REPO_NAME_LC/backend:latest
            
            docker network create workpoint-net || true
            docker stop api-backend || true
            docker rm api-backend || true
            
            docker run -d \
              --name api-backend \
              --restart unless-stopped \
              --network workpoint-net \
              -e Jwt__Key="${{ secrets.JWT_KEY }}" \
              -e Jwt__Issuer="${{ secrets.JWT_ISSUER }}" \
              -e Jwt__Audience="${{ secrets.JWT_AUDIENCE }}" \
              -e ConnectionStrings__DefaultConnection="${{ secrets.DB_CONNECTION_STRING }}" \
              -e CloudinarySettings__CloudName="${{ secrets.CLOUDINARY_CLOUD_NAME }}" \
              -e CloudinarySettings__ApiKey="${{ secrets.CLOUDINARY_API_KEY }}" \
              -e CloudinarySettings__ApiSecret="${{ secrets.CLOUDINARY_API_SECRET }}" \
              ghcr.io/$REPO_NAME_LC/backend:latest
            
            docker image prune -f
            echo " Backend desplegado correctamente"
          EOF
